name: Django tests on master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Format code with black
      run: |
        black .
    - name: 'Create .env file'
      run: |
        touch backend_django/.env
        echo APP_AUTH_TOKEN=${{ secrets.APP_AUTH_TOKEN }} >> backend_django/.env
        echo MS_ENDPOINT=${{ secrets.ENDPOINT }} >> backend_django/.env
        echo MS_PORT=${{ secrets.PORT }} >> backend_django/.env
        echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> backend_django/.env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> backend_djang/.env
        echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> backend_djang/.env
    - name: Run test and coverage report
      run: |
        cd backend_django
        coverage run manage.py test
        coverage report
