name: testing

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.10
        architecture: "x64"
#      env:
#        AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m venv ./venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        echo "VIRTUAL ENV:" $VIRTUAL_ENV

    - name: Format code with black
      run: |
        source venv/bin/activate
        black .
    - name: 'Create env file'
      run: |
        touch backend_django/backend_django/.env
        echo APP_AUTH_TOKEN=${{ secrets.APP_AUTH_TOKEN }} >> backend_django/backend_django/.env
        echo ENDPOINT=${{ secrets.ENDPOINT }} >> backend_django/backend_django/.env
        echo PORT=${{ secrets.PORT }} >> backend_django/backend_django/.env
    - name: Coverage report
      run: |
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        source venv/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        coverage run backend_django/manage.py test
        coverage report
    - name: Run Tests
      run: |
        source venv/bin/activate
        python backend_django/manage.py test
