name: testing

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Format code with black
      run: |
        pip install black
        black .
    - name: 'Create env file'
      run: |
        touch backend_django/backend_django/.env
        echo APP_AUTH_TOKEN=${{ secrets.APP_AUTH_TOKEN }} >> backend_django/backend_django/.env
        echo ENDPOINT=${{ secrets.ENDPOINT }} >> backend_django/backend_django/.env
        echo PORT=${{ secrets.PORT }} >> backend_django/backend_django/.env
    - name: Coverage report
      run: |
        pip install coverage
        coverage run backend_django/manage.py test
        coverage report
    - name: Run Tests
      run: |
        python backend_django/manage.py test
